[package]
name = "iozh"
version = "0.1.0"
edition = "2018"

[dependencies]
pest = "2.5.5"
pest_derive = "2.5.5"
pest_generator = "2.5.5"
pest_meta = "2.5.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
