[package]
name = "iozh_parse"
version = "0.0.0"
edition = "2021"

[lib]

[dependencies]

pest = "2.5.5"
pest_meta = "2.5.5"
pest_derive = "2.5.5"
pest_generator = "2.5.5"

itertools = "0.10.5"
bumpalo = "3.12.0"
lasso = "0.7.0"
quote = "1.0.26"